name = "laluanbas-my"
main = "build/_worker.js"
compatibility_date = "2023-05-18"
pages_build_output_dir = "./out"

[site]
bucket = "./out"

[[env.production.routes]]
pattern = "laluanbasmy.pages.dev/*"
zone_name = "laluanbasmy.pages.dev"